config/routes.rb
require 'sidekiq/web'

Taggregator::Application.routes.draw do
  mount RailsAdmin::Engine => '/railsadmin', :as => 'rails_admin'

  admin_constraint = lambda do |request|
    request.session[:user_id] && User.find(request.session[:user_id]).admin?
  end
  constraints admin_constraint do
    mount Sidekiq::Web, :at => "/sidekiq"
  end

  namespace :admin do
    root to: "root#index"
    post '/daily_email_test' => "root#daily_email_test", :as => "daily_email_test"
    post '/daily_email' => "root#daily_email", :as => "daily_email"
    post '/force_update' => "root#force_update", :as => "force_update"
    resources :subscriptions, :only => [:index, :destroy, :create]
    resources :campaigns do
      member do
        post :set_winning_photo
      end
      collection do
        post :quick_add
      end

      resources :campaign_photos, only: [:index, :update], as: :photos
    end
    resources :tags, only: [:index, :new, :create]
  end    
  match "/auth/instagram/callback" => "sessions#create"
  get "/logout" => "sessions#destroy", :as => "logout"
  get "/email" => "sessions#email", :as => "email"
  post "/email" => "sessions#update_email", :as => "email"
  get "verify" => "sessions#verify", :as => "verify_email"

  get "/instagram/callback" => "realtime#instagram_challenge", :as => :instagram_callback
  post "/instagram/callback" => "realtime#instagram_callback", :as => :instagram_callback
  
  get "/facebook/callback" => "photos#fb_feed_post_callback", :as => :facebook_callback

  resources :tags, only: [:index]

  resources :campaigns, only: [:index, :show] do
    member do
      get :leaderboard
      get :embed
    end
    collection do
      get :top_photos
    end
  end

  resources :photos, only: [:index, :show] do
    collection do
      get :participating_in
    end
    member do
      post :add_to_campaign
    end
  end

  resource :user, only: [] do
    get :profile
    put :update_profile
    get :leaderboard
    match :like
    post :follow
    post :comment
    get :verify
  end
  
  root to: "campaigns#index"
end

app/controllers/admin/root_controller.rb
# Internal: Root admin controller. Shows links to a bunch of other things.
class Admin::RootController < AdminController
  load_and_authorize_resource :campaign, parent: false, only: [:index]

  # Public: Index page for admin panel. Shows links to other admin pages and
  # also gives a quick view of the current campaigns and their recent photos.
  def index
    @campaigns = @campaigns.includes(:photos, :approved_photos).order("end_date DESC").page(params[:page])
  end

  # Public: Shows a list of 'top tags' on Instagram based on the Twitter
  # sprinkle-hose.
  #
  # Aggregates the data out of Redis. Look at the top_statistics rake task for
  # more information about how the data is stored. But basically this fetches
  # all the 10-minute interval data it needs and then aggregates that together
  # in a hash, finally returning a sorted array.
  #
  # Takes a couple of parameters (with defaults)
  #
  # time - How many 10 minute intervals to look back over. Default is 6
  # (one hour). Try '1' for really up to date stats, or 60 for 10 hours worth.
  # count - Total number of tags to display.
  def top_tags

    keys = ((params[:time] && params[:time].to_i) || 6).times.map do |i| 
      at = (i*10).minutes.ago
      "#{at.year}:#{at.month}:#{at.day}:#{at.hour}:#{at.min/10}"
    end

    hashtags = keys.reduce({}) do |acc, k|
      $redis.zrevrange(k, 0, -1, {with_scores: true}).each do |hashtag, value|
        acc[hashtag] = (acc[hashtag] || 0) + value.to_i
      end
      acc
    end

    @tags = hashtags.to_a.sort{|a, b| b.second <=> a.second}.map{|h| {name: h[0], value: h[1]}}.first((params[:count] && params[:count].to_i) || 50)

    respond_to do |format|
      format.html
      format.json { render json: @tags }
    end

  end

  def daily_email
    record = DailyEmail.create!
    redirect_to admin_root_path, notice: "Sending #{record.emails_sent} daily email(s) asynchronously. Check Sidekiq to monitor status."
  end
  
  def daily_email_test
    DailyEmail.test_send_to_admins
    redirect_to admin_root_path, notice: "Sending daily email(s) asynchronously to admins only. Check Sidekiq to monitor status."
  end
  
  def force_update
    Star::PhotoUpdater::Enqueuer.perform_async(true)
    redirect_to admin_root_path, notice: "OK, forced a photo update for all photos in active campaigns. Check Sidekiq to monitor status."
  end

end

app/views/admin/root/_admin_statistics.html.haml
%table.table-striped.table-condensed.table-bordered
  %tbody
    %tr
      %td Number of photos
      %td= Photo.count
    %tr
      %td Number of users
      %td= User.count
    %tr
      %td Users with email addresses
      %td= User.where("email != ''").count
    %tr
      %td Tags we know about
      %td= Tag.count
    %tr
      %td Campaigns running
      %td= Campaign.running.count
    %tr
      %td Photos in running campaigns (approved)
      %td
        = Campaign.running.inject(0){|acc, c| acc + c.photos.count}
        (#{Campaign.running.inject(0){|acc, c| acc + c.approved_photos.count}})

    %tr
      %td Photos in the DB tagged ##{AppConfig.default_hashtag}
      %td= Photo.joins(:photo_tags => :tag).where("tags.name = ?", AppConfig.default_hashtag).count

app/views/admin/root/_quick_add.html.haml
%h1.lead
  Quick Add Campaign

= form_tag quick_add_admin_campaigns_path, method: "POST", class: "form-inline" do
  = text_field_tag :name, nil, placeholder: "Name"
  = text_field_tag :tag, nil, placeholder: "Tag without #", class: "input-small"
  %button.btn{type: "submit"} Create

app/views/admin/root/_sponsor_statistics.html.haml
%p Stats coming soon.

app/views/admin/root/index.html.haml
%h1.lead Statistics

- if current_user.is_sponsor?
  = render partial: "sponsor_statistics"
- elsif current_user.admin?
  = render partial: "admin_statistics"

- if can? :manage, :all
  = render partial: "quick_add"

.pull-right
  = paginate @campaigns
%h1.lead
  Overview of campaigns
  = link_to "New campaign", new_admin_campaign_path, class: "btn btn-primary"


%table#campaigns.table.table-striped.table-bordered
  %thead
    %tr
      %th Campaign Name
      %th Status
      %th Start at
      %th End at
      %th Number of photos (approved)
      %th Photos from #{AppConfig.app_name} users (approved)
      %th Highest rank of an approved photo from #{AppConfig.app_name} user
      %th
  %tbody
    = render @campaigns

.center
  = paginate @campaigns