config/routes.rb
require 'sidekiq/web'

Taggregator::Application.routes.draw do
  mount RailsAdmin::Engine => '/railsadmin', :as => 'rails_admin'

  admin_constraint = lambda do |request|
    request.session[:user_id] && User.find(request.session[:user_id]).admin?
  end
  constraints admin_constraint do
    mount Sidekiq::Web, :at => "/sidekiq"
  end

  namespace :admin do
    root to: "root#index"
    post '/daily_email_test' => "root#daily_email_test", :as => "daily_email_test"
    post '/daily_email' => "root#daily_email", :as => "daily_email"
    post '/force_update' => "root#force_update", :as => "force_update"
    resources :subscriptions, :only => [:index, :destroy, :create]
    resources :campaigns do
      member do
        post :set_winning_photo
      end
      collection do
        post :quick_add
      end

      resources :campaign_photos, only: [:index, :update], as: :photos
    end
    resources :tags, only: [:index, :new, :create]
  end    
  match "/auth/instagram/callback" => "sessions#create"
  get "/logout" => "sessions#destroy", :as => "logout"
  get "/email" => "sessions#email", :as => "email"
  post "/email" => "sessions#update_email", :as => "email"
  get "verify" => "sessions#verify", :as => "verify_email"

  get "/instagram/callback" => "realtime#instagram_challenge", :as => :instagram_callback
  post "/instagram/callback" => "realtime#instagram_callback", :as => :instagram_callback
  
  get "/facebook/callback" => "photos#fb_feed_post_callback", :as => :facebook_callback

  resources :tags, only: [:index]

  resources :campaigns, only: [:index, :show] do
    member do
      get :leaderboard
      get :embed
    end
    collection do
      get :top_photos
    end
  end

  resources :photos, only: [:index, :show] do
    collection do
      get :participating_in
    end
    member do
      post :add_to_campaign
    end
  end

  resource :user, only: [] do
    get :profile
    put :update_profile
    get :leaderboard
    match :like
    post :follow
    post :comment
    get :verify
  end
  
  root to: "campaigns#index"
end

app/models/campaign.rb
# Public: A Campaign, or 'competition' is Taggregator-defined and all photos 
# in it are elligible for the competition. A campaign can have many tags
# (e.g. a campaign for 'Snowy London' might have the tags #snow, #london, and
# #taggregator), and photos are only part of a campaign if they are tagged with
# _all_ the campaign tags. This is so we can use collative tags like
# #taggregator, but might be something we outgrow.
#
# Campaigns/competitions also have a start date, end date and a record of
# whether an email was sent at the start + end of the campaign. They also have
# a reference to the winning photo.
class Campaign < ActiveRecord::Base
  attr_accessible :name, :start_date, :end_date, :tag_tokens,
    :default_approved_state

  validates :name, presence: true
  validates :start_date, :end_date, presence: true

  validate :start_date_must_be_before_end_date

  has_many :campaign_tags, dependent: :delete_all
  has_many :tags, through: :campaign_tags

  has_many :campaign_photos, dependent: :delete_all
  has_many :photos, through: :campaign_photos
  # This is the same join table, just a different name with a condition.
  has_many :approved_photos,
    through: :campaign_photos,
    source: :photo,
    class_name: Photo,
    conditions: {
      campaign_photos: {
        approved: true
      }
    }

  belongs_to :winning_photo, class_name: Photo, inverse_of: :won_campaign

  belongs_to :sponsor

  scope :not_sponsored, -> { where("sponsor_id is NULL") }
  scope :running, -> { where("start_date <= ? and end_date >= ?", Time.now, Time.now) }
  scope :ended_with_winner, -> { where("winning_photo_id IS NOT NULL").order("end_date DESC") }

  before_save :set_default_approved_state_on_existing_photos

  # Public: Fairly self-explanatory. A campaign has ended if the winning
  # photo has been marked.
  def ended?
    winning_photo.present?
  end

  def started?; start_date <= Time.now; end

  # Public: Get the next 'start date' for a campaign. Used for quickly adding
  # a campaign in the admin panel.
  def self.next_start_date
    (Campaign.order("start_date DESC").first.start_date + 1.day).midnight + 10.hours
  end

  # Public: I can't guarantee that this is a good idea.
  #
  # only_emails: Only return participating users we have email addresses for.
  # distinct: Only return unique results, defaults to true.
  def participating_users(only_emails=false, distinct=true)
    condition = "campaigns.id = #{self.id} and campaign_photos.approved = true"
    condition += " AND users.email IS NOT NULL" if only_emails
    result = User.joins(photos: {campaign_photos: :campaign}).where(condition)
    result = result.uniq if distinct
    return result
  end

  # Internal: Translate input from form (which is comma separated) into array for
  # relational assignment.
  def tag_tokens=(ids)
    self.tag_ids = ids.split(",").map(&:to_i)
  end

  def self.quick_add(name, tag_name)
    campaign = new do |c|
      c.name = name
      c.start_date = next_start_date
      c.end_date = c.start_date + AppConfig.default_campaign_length
    end

    tag = Tag.where(name: tag_name).first_or_create
    default_tag = Tag.where(name: AppConfig.default_hashtag).first_or_create
    campaign.tag_ids = [tag.id, default_tag.id]

    campaign.save!
    campaign
  end

  # Internal: Find all photos that meet the criteria to belong to this campaign
  # (tagged with all the campaign tags) and construct join models to link them
  # together.
  def join_to_photos
    # Inverse of #join_to_campaigns
    # Source: http://stackoverflow.com/questions/8425232/sql-select-all-rows-where-subset-exists
    photos_in_campaign = Photo.joins(:photo_tags)
      .select("photos.*, COUNT(photos.id)")
      .where(
        "photo_tags.tag_id IN (:tags) AND photos.created_at < :end_date",
        {tags: self.tags(true),
         end_date: self.end_date})
      .group("photos.id")
      .having("COUNT(photos.id) = #{self.campaign_tags(true).length}")

    self.photos = photos_in_campaign
  end

  # Public: Define both ranked_photos and ranked_approved_photos. You should
  # probably be using the latter.
  %w(photos approved_photos).each do |photo_scope|
    define_method "ranked_#{photo_scope}" do
      self.send(photo_scope).order("campaign_photos.score DESC, id")
    end
  end

  # Deprecated and now you really shouldn't use this 'cos of moderation.
  def photos_count
    self.photos.count
  end

  # Public: Return the top photo.
  def top_photo
    self.ranked_photos.first
  end

  private
  def start_date_must_be_before_end_date
    unless self.start_date < self.end_date
      self.errors.add(:start_date, "must be before end date")
    end
  end

  def set_default_approved_state_on_existing_photos
    if self.default_approved_state_changed?
      campaign_photos.where(moderated: false).update_all(approved: self.default_approved_state)
    end
  end
end

app/controllers/admin/campaigns_controller.rb
# Internal: Controller for managing campaigns. Lets you view, edit and
# create campaigns and send out emails.
class Admin::CampaignsController < AdminController
  load_and_authorize_resource

  def index
    redirect_to admin_root_path
  end

  def show
  end

  def new
  end

  def create
    if @campaign.save
      redirect_to [:admin, @campaign], :notice => "Successfully created campaign."
    else
      render :action => 'new'
    end
  end

  def quick_add
    tag_name = params[:tag]
    tag_name.slice!(0) if tag_name.starts_with? "#"
    campaign = Campaign.quick_add params[:name], tag_name
    if campaign.valid? and campaign.persisted?
      redirect_to admin_root_path, notice: "Successfully quick-added campaign."
    else
      redirect_to admin_root_path, alert: campaign.errors.full_messages.to_sentence
    end
  end

  def edit
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      redirect_to [:admin, @campaign], :notice  => "Successfully updated campaign."
    else
      render :action => 'edit'
    end
  end

  def set_winning_photo
    redirect_to [:admin, @campaign], alert: "That campaign had no photos!" and return if @campaign.approved_photos.count == 0
    winning_photo = @campaign.ranked_photos.first
    @campaign.winning_photo = winning_photo
    @campaign.save

    redirect_to [:admin, @campaign], notice: "OK, set winning photo"
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
    redirect_to admin_root_path, :notice => "Successfully destroyed campaign."
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :load_started_campaign, except: [:index, :top_photos]
  
  # Public: Currently this is the 'home' page when you are not logged in.
  def index
    # Preserve some parameters if the user is logged in.
    redirect_to params.except(:home_page).merge(action: "index", controller: "photos") and return if current_user
    # Not all of these instance variables are used by all iterations of the
    # front page, but at least this way you can pick and choose when designing
    # them.

    @campaigns = Campaign.running.limit(3)
    @finished_campaigns = Campaign.ended_with_winner.order("end_date DESC").limit(3)
    @recent_activity = Rails.cache.fetch("recent_activity", expires_in: 10.minutes) do
      Photo.joins(:campaigns).where(:campaigns => {id: @campaigns}).order("created_at DESC").limit(6)
    end

    respond_to do |format|
      format.html do
        render "campaigns/split_tests/original_design"
      end
      format.json { render json: @campaigns }
    end
  end

  # Returns the 3 running campaigns and their top photos for use in an embedded
  # web view in a mobile app.
  def top_photos
    @campaigns = Campaign.not_sponsored.running.limit(3)
    json = @campaigns.map{|c| CampaignSerializer.new(c, root: false).as_json}
    json.each do |campaign|
      campaign["top_photo"] = PhotoSerializer.new(Campaign.find(campaign[:id]).top_photo, root: false).as_json
    end
    render json: json
  end

  # Show a single campaign & leaderboard
  def show
    @users_photos = @campaign.photos.where(user_id: current_user.id) if current_user
  end

  def embed
    @photos = @campaign.ranked_approved_photos.page(params[:page])
    respond_to do |format|
      format.js
      format.html do
        render layout: "embed"
      end
    end
  end

  # Public: JS endpoint for returning the top 10 photos for a given campaign
  #
  # /campaigns/1/leaderboard
  # # => JSON array of photos.
  def leaderboard
    render json: (@campaign.ranked_approved_photos.first(10) || []), campaign_to_score: @campaign
  end

end

app/helpers/admin/campaigns_helper.rb
module Admin::CampaignsHelper
end

app/views/admin/campaigns/_actions.html.haml
.btn-toolbar
  .btn-group
    = link_to "#", class: "btn btn-success dropdown-toggle", data: {toggle: "dropdown"} do
      Show
      %span.caret
    %ul.dropdown-menu
      %li= link_to "Public", campaign
      %li= link_to "Admin", [:admin, campaign]
      %li= link_to "Embed", embed_campaign_path(campaign)
  .btn-group
    = link_to "#", class: "btn btn-info dropdown-toggle", data: {toggle: "dropdown"} do
      Manage
      %span.caret
    %ul.dropdown-menu
      %li= link_to 'Edit', edit_admin_campaign_path(campaign)
      %li= link_to 'Delete', [:admin, campaign], :confirm => 'Are you sure?', :method => :delete
      %li= link_to 'Moderate', admin_campaign_photos_path(campaign)

app/views/admin/campaigns/_campaign.html.haml
%tr
  %td= campaign.name
  %td
    - if Campaign.running.exists?(campaign)
      Running
    - elsif campaign.start_date > Time.now
      Queued (starting in #{time_ago_in_words(campaign.start_date)})
    - else
      Ended (#{time_ago_in_words(campaign.end_date)} ago)
      - if !campaign.winning_photo.nil?
        and winning photo recorded.
      - else
        but winning photo not recorded.
        = link_to "Record winning photo #{AppConfig.deliver_campaign_emails ? "and email winner" : ""} now", set_winning_photo_admin_campaign_path(campaign), method: :post, confirm: "Are you sure?"
  %td= campaign.start_date.strftime("%Y/%m/%d at %I:%M%p")
  %td= campaign.end_date.strftime("%Y/%m/%d at %I:%M%p")
  %td
    = campaign.photos.count
    (#{campaign.approved_photos.count})
  %td= campaign.participating_users(true, false).length
  %td
    - if campaign.end_date > Time.now
      - r = campaign.ranked_photos.index{|p| p.user.email.present?}
      = r ? r + 1 : "-"
    - else
      Campaign not running
  %td
    = render "admin/campaigns/actions", campaign: campaign

app/views/admin/campaigns/_form.html.haml
= simple_form_for [:admin, @campaign], html: {class: "form-horizontal"} do |f|
  = f.input :name
  = f.input :start_date
  = f.input :end_date
  = f.input :default_approved_state

  .control-group
    %label.control-label Tags:
    .controls
      %input#campaign_tags{name: "campaign[tag_tokens]", type: "text", data: {pre: @campaign.tags.map(&:attributes).to_json}}

      = link_to "New tag", new_admin_tag_path

  = f.button :submit

%p Remember you should probably be adding ##{AppConfig.default_hashtag} as a tag too.

:javascript
  $(function() {
    $("#campaign_tags").tokenInput(Routes.root_path() + "/admin/tags", {
      theme: "facebook",
      prepopulate: $("#campaign_tags").data("pre"),
      crossDomain: false
    });
  });

app/views/admin/campaigns/edit.html.haml
- title "Edit Admin/Campaign"

= render 'form'

%p
  = link_to "Show", [:admin, @campaign]
  |
  = link_to "View All", admin_campaigns_path

app/views/admin/campaigns/new.html.haml
- title "New Admin/Campaign"

= render 'form'

%p= link_to "Back to List", admin_campaigns_path

app/views/admin/campaigns/show.html.haml
- title "Editing #{@campaign.name}"

%h2
  = @campaign.name

  .btn-group
    = link_to "Edit", edit_admin_campaign_path(@campaign), :class => "btn btn-primary"
    = link_to "Destroy", [:admin, @campaign], :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger"
    = link_to "View All", admin_campaigns_path, :class => "btn btn-info"

%table#campaign-info.table-bordered.table-striped.table
  %tr
    %td
      Start Date
    %td
      = @campaign.start_date
  %tr
    %td
      End Date
    %td
      = @campaign.end_date
  %tr
    %td
      Number of photos (approved)
    %td
      #{@campaign.photos.count} (#{@campaign.approved_photos.count})
  %tr
    %td
      Tags
    %td
      = @campaign.tags.map(&:name).to_sentence

%p
  - if @campaign.winning_photo
    %strong Photo that won:
    %br
    = link_to @campaign.winning_photo.url do 
      = image_tag @campaign.winning_photo.thumbnail_url
  - else
    - if @campaign.approved_photos.count > 0 
      - leading_photo = @campaign.ranked_approved_photos.first
      %strong Current leading photo:
      %br
      = link_to leading_photo.url do
        = image_tag leading_photo.thumbnail_url

    %p
      = link_to "Mark as 'won'",
        set_winning_photo_admin_campaign_path(@campaign),
        method: :post,
        class: "btn btn-danger #{@campaign.winning_photo.present? ? "disabled" : ""}",
        confirm: "Are you sure?"

    %p
      You must mark a campaign as 'won' to 'lock in' the winning photo and have it
      mentioned on the daily email and website UI.

%div
  %strong Other photos:
  %br
  - @campaign.ranked_photos.offset(1).each do |photo|
    - present photo do |photo_presenter|
      = photo_presenter.instagram_thumbnail