config/routes.rb
require 'sidekiq/web'

Taggregator::Application.routes.draw do
  mount RailsAdmin::Engine => '/railsadmin', :as => 'rails_admin'

  admin_constraint = lambda do |request|
    request.session[:user_id] && User.find(request.session[:user_id]).admin?
  end
  constraints admin_constraint do
    mount Sidekiq::Web, :at => "/sidekiq"
  end

  namespace :admin do
    root to: "root#index"
    post '/daily_email_test' => "root#daily_email_test", :as => "daily_email_test"
    post '/daily_email' => "root#daily_email", :as => "daily_email"
    post '/force_update' => "root#force_update", :as => "force_update"
    resources :subscriptions, :only => [:index, :destroy, :create]
    resources :campaigns do
      member do
        post :set_winning_photo
      end
      collection do
        post :quick_add
      end

      resources :campaign_photos, only: [:index, :update], as: :photos
    end
    resources :tags, only: [:index, :new, :create]
  end    
  match "/auth/instagram/callback" => "sessions#create"
  get "/logout" => "sessions#destroy", :as => "logout"
  get "/email" => "sessions#email", :as => "email"
  post "/email" => "sessions#update_email", :as => "email"
  get "verify" => "sessions#verify", :as => "verify_email"

  get "/instagram/callback" => "realtime#instagram_challenge", :as => :instagram_callback
  post "/instagram/callback" => "realtime#instagram_callback", :as => :instagram_callback
  
  get "/facebook/callback" => "photos#fb_feed_post_callback", :as => :facebook_callback

  resources :tags, only: [:index]

  resources :campaigns, only: [:index, :show] do
    member do
      get :leaderboard
      get :embed
    end
    collection do
      get :top_photos
    end
  end

  resources :photos, only: [:index, :show] do
    collection do
      get :participating_in
    end
    member do
      post :add_to_campaign
    end
  end

  resource :user, only: [] do
    get :profile
    put :update_profile
    get :leaderboard
    match :like
    post :follow
    post :comment
    get :verify
  end
  
  root to: "campaigns#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :is_admin?, :access_denied, :json_for
  helper :layout

  before_filter :setup_gon

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    klass.new(object, view_context)
  end

  def default_serializer_options
    {root: false}
  end

  private 

  # Manually use serializer
  def json_for(target, options = {})
    options = default_serializer_options.merge(options)
    options[:scope] ||= self
    options[:url_options] ||= url_options
    target.active_model_serializer.new(target, options).to_json
  end

  # Internal: Set up gon variables. Gon allows you to configure stuff
  # server-side and have those variables available in the client-side JS.
  def setup_gon
    gon.logged_in = !current_user.nil?
    if current_user
      gon.access_token = current_user.access_token
    end
  end

  # Public: Filter for checking to make sure the user is logged in and
  # activated.
  def authorized!
    unless current_user and current_user.email.present?
      redirect_to root_path, alert: "You need to be logged in to view that!" and return if !current_user
      redirect_to email_path, alert: "To finish signing up, please supply your email address." and return if current_user.email.blank?
    else
      # WARNING: It is a little DB heavy to do this, but OK for low traffic.
      current_user.update_attributes(last_signed_in_at: Time.now) if !current_user.last_signed_in_at || current_user.last_signed_in_at < 1.hour.ago
    end
  end

  # Public: Filter for making sure the user is logged in + is an admin.
  def admin!
    redirect_to root_path, alert: "Not authorized" and return unless is_admin?
  end

  def admin_or_sponsor!
    redirect_to root_path, alert: "Not authorized!" and return unless is_admin? or is_sponsor?
  end
      

  # Public: Returns the current user or nil.
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] rescue nil
  end

  # Public: True if the current user is an admin 
  def is_admin?
    current_user && current_user.admin?
  end

  def is_sponsor?
    current_user && current_user.sponsor.present?
  end

  # Public: Use to deny a user access to a page.
  def access_denied
    redirect_to main_app.root_url, alert: "Not authorized"
  end

  # Public: Use as a filter to load a campaign and ensure it is started.
  def load_started_campaign
    @campaign = Campaign.find(params[:campaign_id] || params[:id])
    raise ActionController::RoutingError.new('Not Found') unless @campaign.started?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Present an object.
  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end

  # Public: Returns an <li> that has a class of 'active' if the route you
  # supplied is the page the user is currently on.
  #
  # Example:
  #
  #   nav_link("Home", root_path)
  #   # => '<li class="active"><a href="/">Home</a></li>'
  #   # (If the helper is called on the home page)
  def nav_link(text, route)
    content_tag(:li, class: current_page?(route) ? "active" : "") do
      link_to text, route
    end
  end

  # Public: Returns the hash of the current deployed revision.
  # If you're not in production this just returns 'Undeployed'
  def application_revision
    return @revision if @revision
    if !(Rails.env =~ /production/i)
      @revision = 'Undeployed'
    else
      @revision = File.read(File.join(Rails.root, "REVISION"))
    end
  end

  def twitter_intent_url(intent, options)
    "https://twitter.com/intent/#{intent}?#{options.to_param}"
  end
  
  def fb_feed_post_url(photo, campaign, text=nil)
    text = "I'm coming #{photo.position_in(campaign).ordinalize} in '#{campaign.name}' on #{AppConfig.app_name}" unless text
    qs = {
      app_id: AppConfig.facebook.app_id,
      redirect_uri: facebook_callback_url(only_path: false),
      link: root_url(only_path: false),
      picture: photo.image_url,
      name: text,
      caption: photo.caption,
      description: text,
      display: "popup"
    }.to_param
    
    "https://www.facebook.com/dialog/feed?#{qs}"
  end

  def fb_feed_post_win(user, rank)
    qs = {
      app_id: AppConfig.facebook.app_id,
      redirect_uri: facebook_callback_url(only_path: false),
      link: leaderboard_user_url(only_path: false),
      picture: user.profile_picture,
      name: "#{AppConfig.app_name} superstart",
      caption: "The face of a winner!",
      description: "#{user.full_name} is #{rank.ordinalize} in the world on #{AppConfig.app_name}! Check their win!",
      display: "popup"
    }.to_param
    
    "https://www.facebook.com/dialog/feed?#{qs}"
  end

end

app/views/application/_facebook-js-sdk.html.haml
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=#{AppConfig.facebook.app_id}";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/application/_footer.html.haml
.container 
  .row
    .span3
      %p
        %small
          Powered by
          = link_to "Taggregator", "http://github.com/pxiventures/taggregator"
          %br
          = succeed "." do
            Original Tagstar branding by
            = link_to "ORE", "http://www.ore-agency.com/", target: "_blank"


    .span6
      &nbsp;
    .span3
      .pull-right.social-buttons
        = render partial: "application/footer/social_buttons"

app/views/application/_ga.html.haml
:javascript
  window._gaq = window._gaq || [];

- if !(Rails.env =~ /development/i)
  :javascript
    _gaq.push(['_setAccount', '#{AppConfig.analytics_tracking_code}']);
    _gaq.push(['_trackPageview']);

    // Track what type of user this is.
    _gaq.push(['_setCustomVar', 1, 'User Type', '#{current_user ? "Member" : "Visitor"}', 2]);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();

app/views/application/_modals.html.haml
#commentModal.modal.hide.fade
  .modal-header
    %button.close{:data => {dismiss: "modal"}, "aria-hidden" => true} &times;
    %h3 Comment on a photo
  .modal-body
    -# Templated text goes here.
  .modal-footer
    %a.btn{:data => {dismiss: "modal"}, :href => "#"} Cancel
    %a.comment.btn.btn-primary{href: "#", data: {"loading-text" => "Posting..."}} Post comment

#signinModal.modal.hide.fade
  .modal-header
    %button.close{:data => {dismiss: "modal"}, "aria-hidden" => true} &times;
    %h3 Sign in first
  .modal-body
    To do that, you need to sign in with Instagram.
  .modal-footer
    = link_to "Sign in/up with Instagram", "#{root_url}auth/instagram", class: "comment btn btn-success"


#campaignAddModal.modal.hide.fade
  .modal-header
    %button.close{:data => {dismiss: "modal"}, "aria-hidden" => true} &times;
    %h3 Adding photo to competition
  .modal-body
    -# Templated text goes here.
  .modal-footer
    %a.btn{:data => {dismiss: "modal"}, :href => "#"} Don't add
    %a.add.btn.btn-primary{href: "#"} Add to competition

%script#modalCommentTemplate{type: "text/html"}
  %table
    %tr
      %td
        %img{src: "{{image}}"}
      %td
        %p {{caption}}

  %textarea#comment-text{placeholder: "Cool photo, saw it on #{AppConfig.app_name}."}

%script#modalCampaignAddTemplate{type: "text/html"}
  %p
    Are you sure you want to add your photo captioned '{{caption}}' to
    the competition '{{campaign}}'?
  %p
    Doing so will make your Instagram account comment on your photo
    with the tags '{{tags}}'.

#helpModals

  .modal.hide
    .modal-header
      %h3 What is #{AppConfig.app_name}?
    .modal-body
      :markdown

        #{AppConfig.app_name} is a fun way of competing against friends and
        strangers by submitting your best Instagram photos with certain
        hashtags.
        
        Every day a new set of competition hashtags are available for you to
        race your friends to be top of the charts.
        
    .modal-footer
      %a.btn.btn-primary.next{href: "#"} Next

  .modal.hide
    .modal-header
      %h3 How does it work?
    .modal-body
      :markdown
        1. We'll send you daily topics and hashtags.
        2. Tag your Instagram snaps with the competition hashtags, or
           drag-and-drop your photos from the #{AppConfig.app_name} web
           interface.
        3. Watch your best photos rise to the top of the daily leaderboard!
        
    .modal-footer
      %a.btn.btn-primary.next{href: "#"} Next
  
  .modal.hide
    .modal-header
      %h3 How do I win?
    .modal-body
      :markdown
        Just take an amazing picture! 
        
        The better the picture, the greater the chance that your followers and
        #{AppConfig.app_name} users like, 
        comment or follow you. The more likes and comments, the better your
        photo will do!
        
    .modal-footer
      %a.btn.btn-primary.next{href: "#"} Next
  

  .modal.hide
    .modal-header
      %h3 How do I get a higher score on my pictures?
    .modal-body
      :markdown
        #{AppConfig.app_name} uses a special StarScore formula to give everyone
        a fair chance.  If you have thousands of followers it doesn't mean you
        easily beat someone with only 50 followers.
      
    .modal-footer
      %a.btn.btn-success{data: {dismiss: "modal"}, href: "#"} OK, Got it!

app/views/application/_navigation_links.html.haml
- if current_user
  = nav_link "Home", photos_path
- else
  = nav_link "Sign in/up with Instagram", "#{root_path}auth/instagram"
= nav_link "Top Players", leaderboard_user_path
- if current_user
  - if can? :create, Campaign
    = nav_link "Dashboard", admin_root_path

  %li= link_to "Help", "#", id: "help"
  = nav_link "Your Profile", profile_user_path
  %li= link_to "Logout (#{current_user.username})", logout_path

app/views/application/_sign-in-with-instagram.html.haml
= link_to "", current_user ? photos_path : "#{root_path}auth/instagram", id: "start", class: "center"

app/views/application/_templates.html.haml
%script#tagTemplate{type: "text/html"}
  %a.url{href: "{{ url }}", target: "_blank"}
    .info
      {{ name }}
      \-
      {{ value }}

    .cf

%script#userPhotoTemplate{type: "text/html"}
  .campaigns
    %span
      {{#campaigns}}
      {{name}}
      {{/campaigns}}

%script#campaignTemplate{type: "text/html"}
  = image_tag "down-arrow.png", class: "down-arrow"
    

  %h3
    = link_to "{{name}}", campaign_path("id").gsub("id", "{{id}}")
  .tags
    .time-left
      Ends {{end_date}}.
    {{tags_sentence}}


  .photo-wrapper
    .photos
      %p
        %i.icon-spinner.icon-spin
        Loading...

    = link_to campaign_path("id").gsub("id", "{{id}}"), class: "view-more" do
      View more &rarr;

%script#leaderboardPhotoTemplate{type: "text/html"}
  %img.image{src: "{{image_url}}"}
  .position {{position}}
  .details
    .clearfix
    
      .score
        = image_tag "star-monochrome.png"
        {{score}}
    
      %p.attribution
        %img{src: "{{user.profile_picture}}", alt: "{{user.username}}'s profile picture"}
        {{user.username}}
    
    %p.caption {{caption}}

    .buttons
      .btn-group
        %a.btn.btn-small{href: "{{url}}", target: "_blank", title: "View on Instagram"}
          %i.icon-eye-open
        %a.like.btn.btn-small{href: "#", title: "Like/Unlike"} {{{like}}}
        %a.comment.btn.btn-small{href: "#", title: "Comment"}
          %i.icon-comment
        %a.follow.btn.btn-small{href: "#"} {{{following}}}

%script#photoHelpTextTemplate{type: "text/html"}
  .photo.helptext
    = image_tag "right-arrow.png"
    Drag &amp; drop your photos to add them to the competition

app/views/application/_winner.html.haml
.winner
  %h4
    = campaign.name
    %br
    %small
      = time_ago_in_words(campaign.end_date)
      ago
  = link_to campaign, target: "_blank" do
    = image_tag campaign.winning_photo.thumbnail_url